apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  volumes:
    - name: sample
      emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: sample
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date > /var/log/index.html; sleep 10; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /var/log