apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    env:
    - name: DEMO-2
      value: "Hello from the environment"
    - name: DEMO-1
      value: "Such a sweet sorrow"
