apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.6
    env:
      - name: URL
        value: google.com
