apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: burlash.azurecr.io/frontend:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  clusterIP:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: clusterip-debug
# spec:
#   containers:
#   - name: redhat
#     image: rkalluru/learnk8s:rhel9-bare
