apiVersion: v1
kind: Pod
metadata:
  name: roboshop-frontend
  labels:
    app: roboshop-frontend
spec:
  containers:
    - name: roboshop-frontend
      image: burlash.azurecr.io/frontend:latest
      imagePullPolicy: Always
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-frontend
spec:
  type: LoadBalancer
  selector:
    app: roboshop-frontend
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-catalogue
  labels:
    app: roboshop-catalogue
spec:
  containers:
    - name: roboshop-catalogue
      image: burlash.azurecr.io/catalogue:latest
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: roboshop-catalogue
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-catalogue
spec:
  selector:
    app: roboshop-catalogue
  ports:
    - protocol: TCP
      port: 8002 # Service Port
      targetPort: 8002 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-user
  labels:
    app: roboshop-user
spec:
  containers:
    - name: roboshop-user
      image: burlash.azurecr.io/user:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-user
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-user
spec:
  selector:
    app: roboshop-user
  ports:
    - protocol: TCP
      port: 8001 # Service Port
      targetPort: 8001 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-cart
  labels:
    app: roboshop-cart
spec:
  containers:
    - name: roboshop-cart
      image: burlash.azurecr.io/cart:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-cart
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-cart
spec:
  selector:
    app: roboshop-cart
  ports:
    - protocol: TCP
      port: 8003 # Service Port
      targetPort: 8003 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-shipping
  labels:
    app: roboshop-shipping
spec:
  containers:
    - name: roboshop-shipping
      image: burlash.azurecr.io/shipping:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-shipping
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-shipping
spec:
  selector:
    app: roboshop-shipping
  ports:
    - protocol: TCP
      port: 8004 # Service Port
      targetPort: 8004 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-payment
  labels:
    app: roboshop-payment
spec:
  containers:
    - name: roboshop-payment
      image: burlash.azurecr.io/payment:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-payment
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-payment
spec:
  selector:
    app: roboshop-payment
  ports:
    - protocol: TCP
      port: 8005 # Service Port
      targetPort: 8005 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-ratings
  labels:
    app: roboshop-ratings
spec:
  containers:
    - name: roboshop-ratings
      image: burlash.azurecr.io/ratings:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-ratings
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-ratings
spec:
  selector:
    app: roboshop-ratings
  ports:
    - protocol: TCP
      port: 8006 # Service Port
      targetPort: 8006 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-orders
  labels:
    app: roboshop-orders
spec:
  containers:
    - name: roboshop-orders
      image: burlash.azurecr.io/orders:latest
      imagePullPolicy: Always
      envFrom:
          - configMapRef:
              name: roboshop-orders
  
---
apiVersion: v1
kind: Service
metadata:
  name: roboshop-orders
spec:
  selector:
    app: roboshop-orders
  ports:
    - protocol: TCP
      port: 8007 # Service Port
      targetPort: 8007 # Container Port

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-cart
data:
  REDIS_HOST : valkey-dev.shashidevops.online
  CATALOGUE_URL : http://roboshop-catalogue:8002
  PORT : "8003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-catalogue
data:
  MYSQL_HOST : mysql-dev.shashidevops.online
  MYSQL_USER : catalogue
  MYSQL_PASSWORD : RoboShop@1
  MYSQL_ROOT_PASSWORD : RoboShop@1
  MYSQL_DATABASE : catalogue
  PORT : "8002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-user
data:
  MONGO_URL : mongodb://mongodb-dev.shashidevops.online:27017/users
  JWT_SECRET : roboshop-secret-key
  PORT : "8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-shipping
data:
  DB_HOST : mysql-dev.shashidevops.online
  DB_USER : shipping
  DB_PASS : RoboShop@1
  MYSQL_ROOT_PASSWORD : RoboShop@1
  PORT : "8004"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-payment
data:
  AMQP_HOST : rabbitmq-dev.shashidevops.online
  AMQP_USER : roboshop
  AMQP_PASS : RoboShop@1
  CART_URL : http://roboshop-cart:8003
  USER_URL : http://roboshop-user:8001
  PORT : "8005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-orders
data:
  MONGO_URL : mongodb://mongodb-dev.shashidevops.online:27017/orders
  AMQP_HOST : rabbitmq-dev.shashidevops.online
  AMQP_USER : roboshop
  AMQP_PASS : RoboShop@1
  SHIPPING_URL : http://roboshop-shipping:8004
  NOTIFICATION_URL : http://localhost:8008
  PORT : "8007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-ratings
data:
  MYSQL_HOST : mysql-dev.shashidevops.online
  MYSQL_USER : ratings
  MYSQL_PASSWORD : RoboShop@1
  MYSQL_ROOT_PASSWORD : RoboShop@1
  MYSQL_DATABASE : ratings
  PORT : "8006"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: roboshop-catalogue-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: catalogue-db
        image: burlash.azurecr.io/catalogue-db
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: roboshop-catalogue

---
apiVersion: batch/v1
kind: Job
metadata:
  name: roboshop-ratings-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: roboshop-ratings-db
        image: burlash.azurecr.io/ratings-db
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: roboshop-ratings
---
apiVersion: batch/v1
kind: Job
metadata:
  name: roboshop-shipping-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: roboshop-shipping-db
        image: burlash.azurecr.io/shipping-db
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: roboshop-shipping
---
apiVersion: batch/v1
kind: Job
metadata:
  name: roboshop-user-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: roboshop-user-db
        image: burlash.azurecr.io/user-db
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: roboshop-user
