apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset01
  labels:
    app: daemonset-demo
spec:
  selector:
    matchLabels:
      app: daemonset-demo
  template:
    metadata:
      labels:
        app: daemonset-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25